"""empty message

Revision ID: 0691eb77c8e3
Revises: af236609e17a
Create Date: 2020-06-14 19:25:35.954952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0691eb77c8e3'
down_revision = 'af236609e17a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'was_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'was_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
