"""empty message

Revision ID: 57dda3d14b23
Revises: ad108dec7885
Create Date: 2020-05-29 22:49:55.966723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57dda3d14b23'
down_revision = 'ad108dec7885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('contact_group', sa.String(length=16), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'contact_id')
    )
    op.drop_table('user_contacts_association')
    op.alter_column('roles', 'permissions',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'permissions',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_table('user_contacts_association',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contact_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contact_group', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['users.id'], name='user_contacts_association_contact_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_contacts_association_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'contact_id', name='user_contacts_association_pkey')
    )
    op.drop_table('contacts')
    # ### end Alembic commands ###
