"""empty message

Revision ID: 88447bb61856
Revises: 5e3b4e0036c8
Create Date: 2020-05-22 17:20:59.026719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88447bb61856'
down_revision = '5e3b4e0036c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.alter_column('users', 'confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'confirmed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('users', 'last_seen')
    op.alter_column('roles', 'name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###
