"""empty message

Revision ID: ad108dec7885
Revises: 88447bb61856
Create Date: 2020-05-24 23:17:44.340956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad108dec7885'
down_revision = '88447bb61856'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('is_default', sa.Boolean(), nullable=False))
    op.add_column('roles', sa.Column('permissions', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_roles_is_default'), 'roles', ['is_default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_is_default'), table_name='roles')
    op.drop_column('roles', 'permissions')
    op.drop_column('roles', 'is_default')
    # ### end Alembic commands ###
