"""empty message

Revision ID: af236609e17a
Revises: 57dda3d14b23
Create Date: 2020-06-14 19:23:40.309439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af236609e17a'
down_revision = '57dda3d14b23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('was_read', sa.Boolean()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'was_read')
    # ### end Alembic commands ###
